kind: Pod
apiVersion: v1
metadata:
  name: dummy
  namespace: default
spec:
  containers:
    - name: dummy
      image: vvang/dummy:amd64
# optional
      securityContext:
        privileged: true
        runAsUser: 0

